import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import {gql, useQuery} from '@apollo/client';

const getAllUsersQuery = gql`
  query {
    getUsers {
      id
      name
      posts {
        id
        title
      }
      createdAt
      updatedAt
    }
  }
`

const getAllPostsQuery = gql`
  query {
    getPosts {
      id
      title
      content
      authorId
      author {
        id
        name
      }
      createdAt
      updatedAt
    }
  }
`

const Home: NextPage = () => {
  const {data, loading, error} = useQuery(getAllUsersQuery);
  const {data: postsData, error: getPostsError } = useQuery(getAllPostsQuery);

  if (loading) return <p>Loading...</p>
  if (error) return <p>Error: {error.message}</p>

  console.log(postsData);
  console.log(getPostsError);

  const users = data?.getUsers ?? [];
  const posts = postsData?.getPosts ?? [];

  console.log(users);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ul>
          {users.map((user) => (
            <li key={user.id}>
              <p>{user.name}: {user.createdAt}</p>
              <ul>
                {user.posts.map((post) =>
                <li key={post.id}>
                  <p>{post.title} : {post.createdAt}</p>
                </li>                      
                )}
              </ul>
            </li>
          ))}
        </ul>
        <ul>
          {posts.map((post) => (
            <li key={post.id}>
              <p>{post.title} - {post.author?.name} : {post.createdAt}</p>
            </li>
          ))}
        </ul>
      </main>

    </div>
  )
}

export default Home
