import type { NextPage } from 'next'
import { useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import {gql, useQuery, useMutation} from '@apollo/client';

const getAllUsersQuery = gql`
  query {
    getUsers {
      id
      name
      posts {
        id
        title
      }
      createdAt
      updatedAt
    }
  }
`

const getAllPostsQuery = gql`
  query {
    getPosts {
      id
      title
      content
      authorId
      author {
        id
        name
      }
      createdAt
      updatedAt
    }
  }
`

const createUserQuery = gql`
  mutation CreateUser($name: String!) {
    createUser(input: {name: $name}) {
      id
      name
      createdAt
      updatedAt
    }
  }
`

const Home: NextPage = () => {
  const [userName, setUserName] = useState<string>();

  const {data, loading, error} = useQuery(getAllUsersQuery);
  const {data: postsData } = useQuery(getAllPostsQuery);

  const [createUser] = useMutation(createUserQuery, {
    refetchQueries: [
      getAllUsersQuery
    ]
  });

  if (loading) return <p>Loading...</p>
  if (error) return <p>Error: {error.message}</p>

  const users = data?.getUsers ?? [];
  const posts = postsData?.getPosts ?? [];

  const submitForUser = () => {
    createUser({
      variables: {
        name: userName
      }
    })
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <input type="text" value={userName} onChange={(event: Event)=> {
        setUserName(event.target.value);
      }} />
      <button onClick={submitForUser}>CreateUser</button>

      <main className={styles.main}>
        <ul>
          {users.map((user) => (
            <li key={user.id}>
              <p>{user.name}: {user.createdAt}</p>
              <ul>
                {user.posts.map((post) =>
                <li key={post.id}>
                  <p>{post.title} : {post.createdAt}</p>
                </li>                      
                )}
              </ul>
            </li>
          ))}
        </ul>
        <ul>
          {posts.map((post) => (
            <li key={post.id}>
              <p>{post.title} - {post.author?.name} : {post.createdAt}</p>
            </li>
          ))}
        </ul>
      </main>

    </div>
  )
}

export default Home
